<?php

return [

    'OTP_TIME'=> 5,

    'USER_STATUS_ACTIVE'=>1,

    // status code
    'LOGIN_SUCCESS'=>101,
    'LOGIN_FAILED'=>102,
    'REGISTER_SUCCESS'=>103,
    'REGISTER_FAILED'=>104,
    'USER_INVITATION_SUCCESS'=>105,
    'USER_INVITATION_FAILED'=>106,
    'INVALID_REQUEST'=>106,
    'OTP_FAILED'=>107,
    'OTP_SUCCESS'=>108,
    'PROFILE_UPDATE_SUCCESS'=>109,
    'PROFILE_UPDATE_FAILED'=>110,
];